Previously watched
sschipke-conga/black-stories-fe pull request #36
Opened 2021-02-09 21:47 UTC by nathanielmillard

## What's this PR do?
-Renames the GenrePage to Movie List
-Recycles this components to create a previously watched page

### How should this be manually tested?
-Navigate to previously watched from the nav menu

### What are the relevant issues/tickets?

#### Screenshots (if appropriate)
![Screen Shot 2021-02-09 at 2 46 48 PM](https://user-images.githubusercontent.com/65516564/107432764-a5ffec80-6ae5-11eb-939f-a27c440f643f.png)

2021-02-09 23:31 UTC, sschipke requested changes
### Observations:

- [ ] When I look at a specific movie from the "Previously Watched List" the runtime is displaying as `NAN`
![Screen Shot 2021-02-09 at 4 12 37 PM](https://user-images.githubusercontent.com/49662828/107440908-a1d9cc00-6af1-11eb-8083-a39b013225bc.png)

- [ ] In the mobile view, the previously watched movies are rendered outside of their container and off the page 
![602305b3cfe20e00078e5fca--blackstories-dev netlify app_previouslywatched(iPhone 6_7_8)](https://user-images.githubusercontent.com/49662828/107441203-16ad0600-6af2-11eb-9f75-d2cb8f0bdadb.png)

- [ ] The film information on the "Previously Watched Page" should display only the following (see comp for examples): 
- Movie Poster
- Title
- Date Watched (`date_watched`)
- Who in the group chose the movie (`chosen_by`)

- [ ] The movies should be in chronological order by their `date_watched` which is to say, the first movie chosen should be at the top, with the most current movies at the bottom.

2021-02-09 23:31 UTC, sschipke commented on src/containers/MovieList/MovieList.scss
> +
Per the comp, I believe this background gradient should be #FDE997 to #FF3399
[Hex Values Here](https://docs.google.com/document/d/18rHWoStJw2ZglnNJvR-GAYEimz3G4wb1BwgdejUGQ98)
## Screenshot of comp
![Screen Shot 2021-02-09 at 4 03 48 PM](https://user-images.githubusercontent.com/49662828/107440146-668acd80-6af0-11eb-96f6-842aff830a61.png)

2021-02-17 18:25 UTC, nathanielmillard commented on src/containers/MovieList/MovieList.scss
> +
Taken care of! Thanks!

2021-02-17 20:35 UTC, nathanielmillard commented
It looks like the previous watch data doesn't have the run time stored, so I am going to have some error handling to only include the run time if it's listed until we can updated the data.

2021-02-24 03:30 UTC, sschipke-conga approved these changes

2021-02-24 03:30 UTC, merged